"""Add User Table

Revision ID: 391e4dd91fee
Revises: dc2fb93a0e72
Create Date: 2024-12-20 15:41:47.626734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391e4dd91fee'
down_revision = 'dc2fb93a0e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
